
-- Insert Data for Admin Logs Table
INSERT INTO AdminLogs (AdminID, Action, Timestamp) VALUES
(1, 'Updated user permissions.', GETDATE()),
(2, 'Deleted an inactive account.', GETDATE()),
(3, 'Added a new administrator.', GETDATE()),
(4, 'Reviewed system security logs.', GETDATE()),
(5, 'Reset a user password.', GETDATE()),
(6, 'Modified subscription plans.', GETDATE()),
(7, 'Approved a refund request.', GETDATE()),
(8, 'Disabled a flagged user account.', GETDATE()),
(9, 'Reviewed transaction history.', GETDATE()),
(10, 'Sent an announcement to all users.', GETDATE()),
(11, 'Changed website maintenance mode.', GETDATE()),
(12, 'Removed a duplicate transaction.', GETDATE()),
(13, 'Updated admin policies.', GETDATE()),
(14, 'Reviewed customer complaints.', GETDATE()),
(15, 'Issued a warning to a user.', GETDATE()),
(16, 'Adjusted payment gateway settings.', GETDATE()),
(17, 'Reviewed API access logs.', GETDATE()),
(18, 'Approved a withdrawal request.', GETDATE()),
(19, 'Verified an email change request.', GETDATE()),
(20, 'Revoked a suspicious admin session.', GETDATE()),
(21, 'Updated website terms of service.', GETDATE()),
(22, 'Investigated a reported bug.', GETDATE()),
(23, 'Fixed a UI issue on the admin dashboard.', GETDATE()),
(24, 'Reviewed backup logs.', GETDATE()),
(25, 'Locked an account due to multiple failed logins.', GETDATE()),
(26, 'Enabled advanced security features.', GETDATE()),
(27, 'Reviewed audit logs.', GETDATE()),
(28, 'Banned a user for policy violations.', GETDATE()),
(29, 'Sent a notification about an update.', GETDATE()),
(30, 'Changed password policy rules.', GETDATE()),
(31, 'Monitored API request logs.', GETDATE()),
(32, 'Updated site-wide notification banner.', GETDATE()),
(33, 'Updated pricing details.', GETDATE()),
(34, 'Revoked a compromised session.', GETDATE()),
(35, 'Reviewed server error logs.', GETDATE()),
(36, 'Disabled a reported phishing attempt.', GETDATE()),
(37, 'Manually processed a refund.', GETDATE()),
(38, 'Investigated failed login attempts.', GETDATE()),
(39, 'Checked for unauthorized API calls.', GETDATE()),
(40, 'Reviewed administrator access logs.', GETDATE()),
(41, 'Investigated slow server performance.', GETDATE()),
(42, 'Tested new security patches.', GETDATE()),
(43, 'Manually verified a pending transaction.', GETDATE()),
(44, 'Changed email notification settings.', GETDATE()),
(45, 'Updated admin interface layout.', GETDATE()),
(46, 'Blocked an IP address due to suspicious activity.', GETDATE()),
(47, 'Reviewed stored session tokens.', GETDATE()),
(48, 'Modified user verification settings.', GETDATE()),
(49, 'Generated a system performance report.', GETDATE()),
(50, 'Assigned a new moderator role.', GETDATE()),
(51, 'Updated fraud detection rules.', GETDATE()),
(52, 'Cleared outdated cache logs.', GETDATE()),
(53, 'Enabled additional security audits.', GETDATE()),
(54, 'Investigated unauthorized login attempts.', GETDATE()),
(55, 'Reviewed encryption settings.', GETDATE()),
(56, 'Updated terms and conditions.', GETDATE()),
(57, 'Re-enabled a suspended account.', GETDATE());
