-- Insert Data for Notifications Table
INSERT INTO Notifications (UserID, Message, Status, CreatedAt) VALUES
(1, 'Your refund request has been processed.', 'Unread', GETDATE()),
(2, 'New security update available.', 'Unread', GETDATE()),
(3, 'Your profile has been updated.', 'Read', GETDATE()),
(4, 'Payment received successfully.', 'Unread', GETDATE()),
(5, 'Your password was changed.', 'Read', GETDATE()),
(6, 'Subscription renewed successfully.', 'Unread', GETDATE()),
(7, 'Your withdrawal request is pending.', 'Unread', GETDATE()),
(8, 'A new login detected from an unknown device.', 'Read', GETDATE()),
(9, 'Your account verification is complete.', 'Unread', GETDATE()),
(10, 'Your transaction has been completed.', 'Read', GETDATE()),
(11, 'New promotional offer available.', 'Unread', GETDATE()),
(12, 'Payment method updated successfully.', 'Read', GETDATE()),
(13, 'Your request for account deletion has been received.', 'Unread', GETDATE()),
(14, 'A new message from customer support.', 'Unread', GETDATE()),
(15, 'Scheduled maintenance will occur tomorrow.', 'Read', GETDATE()),
(16, 'A new device was added to your account.', 'Unread', GETDATE()),
(17, 'Your account settings have been changed.', 'Read', GETDATE()),
(18, 'Refund request has been declined.', 'Unread', GETDATE()),
(19, 'Reminder: Subscription renewal due.', 'Unread', GETDATE()),
(20, 'Your referral bonus has been credited.', 'Read', GETDATE()),
(21, 'New feature update is now available.', 'Unread', GETDATE()),
(22, 'A suspicious login attempt detected.', 'Read', GETDATE()),
(23, 'Congratulations! You’ve won a giveaway.', 'Unread', GETDATE()),
(24, 'Your profile information has been updated.', 'Unread', GETDATE()),
(25, 'A new alert from security team.', 'Read', GETDATE()),
(26, 'Scheduled downtime notification.', 'Unread', GETDATE()),
(27, 'Password reset request received.', 'Unread', GETDATE()),
(28, 'Transaction limit has been increased.', 'Read', GETDATE()),
(29, 'Your email has been successfully verified.', 'Unread', GETDATE()),
(30, 'Payment pending, please check your balance.', 'Unread', GETDATE()),
(31, 'Your two-factor authentication was disabled.', 'Read', GETDATE()),
(32, 'You have received a gift card.', 'Unread', GETDATE()),
(33, 'Subscription successfully canceled.', 'Read', GETDATE()),
(34, 'A new contact request received.', 'Unread', GETDATE()),
(35, 'Your credit card details were updated.', 'Read', GETDATE()),
(36, 'Your order has been shipped.', 'Unread', GETDATE()),
(37, 'New message from customer support.', 'Unread', GETDATE()),
(38, 'Your refund request is being reviewed.', 'Unread', GETDATE()),
(39, 'Your recent transaction has been declined.', 'Read', GETDATE()),
(40, 'Your loyalty points have been updated.', 'Unread', GETDATE()),
(41, 'Subscription upgraded successfully.', 'Read', GETDATE()),
(42, 'Reminder: Payment due tomorrow.', 'Unread', GETDATE()),
(43, 'Security alert: Change detected in login pattern.', 'Read', GETDATE()),
(44, 'Your billing address has been updated.', 'Unread', GETDATE()),
(45, 'New survey available, share your feedback.', 'Unread', GETDATE()),
(46, 'Limited-time discount on premium plans.', 'Read', GETDATE()),
(47, 'Your request for data export is ready.', 'Unread', GETDATE()),
(48, 'Failed login attempt detected.', 'Read', GETDATE()),
(49, 'Your API key has been generated.', 'Unread', GETDATE()),
(50, 'Your refund request has been approved.', 'Unread', GETDATE()),
(51, 'New blog post available on our website.', 'Read', GETDATE()),
(52, 'A new transaction alert for your account.', 'Unread', GETDATE()),
(53, 'Changes detected in your security settings.', 'Read', GETDATE()),
(54, 'Reminder: Update your profile information.', 'Unread', GETDATE()),
(55, 'Your service request has been resolved.', 'Read', GETDATE()),
(56, 'System update completed successfully.', 'Unread', GETDATE()),
(57, 'Payment received from your linked account.', 'Unread', GETDATE());
