-- Insert Data for SupportTickets Table
INSERT INTO SupportTickets (UserID, Subject, Message, Status, CreatedAt) VALUES
(1, 'Login Issue', 'Unable to log in with my credentials.', 'Open', GETDATE()),
(2, 'Payment Failure', 'My payment is not being processed.', 'Pending', GETDATE()),
(3, 'Refund Request', 'Requesting a refund for my last transaction.', 'Closed', GETDATE()),
(4, 'Account Suspension', 'My account was suspended without notice.', 'Open', GETDATE()),
(5, 'Subscription Cancellation', 'I want to cancel my subscription.', 'Pending', GETDATE()),
(6, 'Two-Factor Authentication Issue', 'Not receiving authentication codes.', 'Open', GETDATE()),
(7, 'Profile Update Error', 'Unable to update my profile details.', 'Closed', GETDATE()),
(8, 'Security Concern', 'Suspicious activity detected on my account.', 'Open', GETDATE()),
(9, 'Feature Request', 'Can you add dark mode to the UI?', 'Pending', GETDATE()),
(10, 'Bug Report', 'Found a glitch in the payment system.', 'Closed', GETDATE()),
(11, 'Login Delay', 'Experiencing slow login times.', 'Open', GETDATE()),
(12, 'Order Not Delivered', 'Haven’t received my product yet.', 'Pending', GETDATE()),
(13, 'Transaction Issue', 'My transaction is stuck in processing.', 'Closed', GETDATE()),
(14, 'Account Recovery', 'Lost access to my account.', 'Open', GETDATE()),
(15, 'Subscription Upgrade', 'Requesting an upgrade to a premium plan.', 'Pending', GETDATE()),
(16, 'Mobile App Issue', 'App keeps crashing on my device.', 'Open', GETDATE()),
(17, 'Email Verification', 'Not receiving email verification code.', 'Closed', GETDATE()),
(18, 'Password Reset', 'Unable to reset my password.', 'Open', GETDATE()),
(19, 'Loyalty Points Issue', 'My points are not updating correctly.', 'Pending', GETDATE()),
(20, 'Unauthorized Charge', 'Detected an unauthorized charge on my card.', 'Closed', GETDATE()),
(21, 'Account Deletion Request', 'Requesting permanent account deletion.', 'Open', GETDATE()),
(22, 'Service Downtime', 'Service was down yesterday for an hour.', 'Pending', GETDATE()),
(23, 'New Payment Method', 'How can I add a new payment method?', 'Closed', GETDATE()),
(24, 'Incorrect Billing', 'Charged twice for the same service.', 'Open', GETDATE()),
(25, 'VPN Access Issue', 'VPN access not working.', 'Pending', GETDATE()),
(26, 'File Upload Problem', 'Unable to upload documents.', 'Open', GETDATE()),
(27, 'Data Export Request', 'Requesting a full export of my account data.', 'Closed', GETDATE()),
(28, 'Notification Delay', 'Not receiving system notifications on time.', 'Open', GETDATE()),
(29, 'Subscription Renewal', 'Want to confirm my subscription renewal.', 'Pending', GETDATE()),
(30, 'Affiliate Program', 'Interested in joining the affiliate program.', 'Closed', GETDATE()),
(31, 'Transaction Reversal', 'Need to reverse a failed transaction.', 'Open', GETDATE()),
(32, 'Content Access Issue', 'Premium content is not accessible.', 'Pending', GETDATE()),
(33, 'New User Registration Problem', 'Cannot sign up with my email.', 'Closed', GETDATE()),
(34, 'Privacy Policy Inquiry', 'Have questions about data privacy.', 'Open', GETDATE()),
(35, 'Beta Program Access', 'Requesting access to beta features.', 'Pending', GETDATE()),
(36, 'Discount Code Not Working', 'My discount code is not applying.', 'Open', GETDATE()),
(37, 'Multiple Charges', 'Charged multiple times for the same order.', 'Closed', GETDATE()),
(38, 'Service Request', 'Need assistance with an order.', 'Open', GETDATE()),
(39, 'IP Restriction Issue', 'Cannot access my account from my country.', 'Pending', GETDATE()),
(40, 'Product Review Request', 'Can I submit a review for a product?', 'Closed', GETDATE()),
(41, 'Account Lockout', 'Locked out of my account.', 'Open', GETDATE()),
(42, 'Referral Program Inquiry', 'How does the referral system work?', 'Pending', GETDATE()),
(43, 'Cloud Storage Issue', 'My uploaded files are missing.', 'Open', GETDATE()),
(44, 'Dark Mode Request', 'Would love to see a dark mode feature.', 'Closed', GETDATE()),
(45, 'Mobile Number Update', 'Need to update my phone number.', 'Open', GETDATE()),
(46, 'Downgrade Subscription', 'Want to switch to a cheaper plan.', 'Pending', GETDATE()),
(47, 'Payment Refund Delay', 'Still waiting for my refund.', 'Closed', GETDATE()),
(48, 'Server Timeout', 'Website is not loading properly.', 'Open', GETDATE()),
(49, 'Personalized Offers Inquiry', 'How do I get personalized discounts?', 'Pending', GETDATE()),
(50, 'Address Update', 'Changed my residence, need to update.', 'Closed', GETDATE()),
(51, 'Lost Subscription Benefits', 'Lost access to premium content.', 'Open', GETDATE()),
(52, 'Error 500 on Dashboard', 'Getting an internal server error.', 'Pending', GETDATE()),
(53, 'Security Upgrade', 'Want to enable additional security features.', 'Closed', GETDATE()),
(54, 'Access Denied Error', 'Restricted access to my account.', 'Open', GETDATE()),
(55, 'Slow Response Time', 'Website takes too long to load.', 'Pending', GETDATE()),
(56, 'New Feature Suggestion', 'Would love an AI assistant feature.', 'Closed', GETDATE()),
(57, 'Cancel Pending Order', 'Want to cancel an order before shipping.', 'Open', GETDATE());
