-- Insert Data for UsageHistory Table
INSERT INTO UsageHistory (UserID, ActivityType, Details, Timestamp) VALUES
(1, 'Login', 'User logged into the system.', GETDATE()),
(2, 'API Request', 'Requested data from API endpoint.', GETDATE()),
(3, 'Subscription Renewal', 'Renewed Premium Plan subscription.', GETDATE()),
(4, 'Payment', 'Completed payment for invoice #12345.', GETDATE()),
(5, 'Profile Update', 'Updated email and phone number.', GETDATE()),
(6, 'Password Reset', 'Requested password reset.', GETDATE()),
(7, 'Logout', 'User logged out of the system.', GETDATE()),
(8, 'Two-Factor Authentication', 'Enabled 2FA for account security.', GETDATE()),
(9, 'Download', 'Downloaded monthly usage report.', GETDATE()),
(10, 'Login', 'User logged into the system.', GETDATE()),
(11, 'API Key Generated', 'Created a new API key.', GETDATE()),
(12, 'Data Export', 'Exported transaction history.', GETDATE()),
(13, 'Bug Report', 'Reported an issue in the dashboard.', GETDATE()),
(14, 'Settings Update', 'Updated notification preferences.', GETDATE()),
(15, 'Subscription Upgrade', 'Upgraded to Enterprise Plan.', GETDATE()),
(16, 'Login', 'User logged into the system.', GETDATE()),
(17, 'Transaction Failure', 'Attempted but failed payment.', GETDATE()),
(18, 'Support Ticket', 'Opened a support ticket for billing.', GETDATE()),
(19, 'Login', 'User logged into the system.', GETDATE()),
(20, 'Order Placement', 'Placed an order for digital service.', GETDATE()),
(21, 'Logout', 'User logged out of the system.', GETDATE()),
(22, 'File Upload', 'Uploaded documents for verification.', GETDATE()),
(23, 'Referral Program', 'Invited a friend to join the platform.', GETDATE()),
(24, 'Security Alert', 'Unusual login attempt detected.', GETDATE()),
(25, 'API Request', 'Fetched analytics data via API.', GETDATE()),
(26, 'Settings Update', 'Changed default currency settings.', GETDATE()),
(27, 'Feature Request', 'Suggested adding an AI assistant.', GETDATE()),
(28, 'Account Deletion Request', 'Requested account deletion.', GETDATE()),
(29, 'Subscription Cancellation', 'Canceled Standard Plan subscription.', GETDATE()),
(30, 'Login', 'User logged into the system.', GETDATE()),
(31, 'Order Cancellation', 'Canceled pending order.', GETDATE()),
(32, 'Transaction Reversal', 'Reversed an incorrect transaction.', GETDATE()),
(33, 'Login', 'User logged into the system.', GETDATE()),
(34, 'Subscription Purchase', 'Purchased Basic Plan subscription.', GETDATE()),
(35, 'Download', 'Downloaded API usage statistics.', GETDATE()),
(36, 'Login', 'User logged into the system.', GETDATE()),
(37, 'Login Attempt Failed', 'Failed login due to incorrect password.', GETDATE()),
(38, 'Settings Update', 'Updated language preferences.', GETDATE()),
(39, 'Referral Reward', 'Received reward for successful referral.', GETDATE()),
(40, 'Support Ticket', 'Raised issue regarding late refunds.', GETDATE()),
(41, 'Security Update', 'Changed account password.', GETDATE()),
(42, 'Mobile App Login', 'Logged in via mobile app.', GETDATE()),
(43, 'Data Request', 'Requested backup of account data.', GETDATE()),
(44, 'Logout', 'User logged out of the system.', GETDATE()),
(45, 'Service Downtime Report', 'Reported platform downtime.', GETDATE()),
(46, 'Payment Confirmation', 'Confirmed successful payment.', GETDATE()),
(47, 'Bug Fix Verification', 'Tested and verified a bug fix.', GETDATE()),
(48, 'Login', 'User logged into the system.', GETDATE()),
(49, 'Refund Processed', 'Received refund for failed order.', GETDATE()),
(50, 'Address Change', 'Updated shipping address.', GETDATE()),
(51, 'Login', 'User logged into the system.', GETDATE()),
(52, 'Failed API Authentication', 'Invalid API key used.', GETDATE()),
(53, 'Security Concern Raised', 'Reported unauthorized login attempt.', GETDATE()),
(54, 'Transaction Approval', 'Approved pending transaction.', GETDATE()),
(55, 'Account Locked', 'Account locked after multiple failed logins.', GETDATE()),
(56, 'Usage Analysis', 'Checked usage reports on dashboard.', GETDATE()),
(57, 'Login', 'User logged into the system.', GETDATE());
